### PR TITLE
lme4 1.1-8 fixes: maxit hacks

### PR DESCRIPTION
**Pull request by bbolker**
hi Vince,

I had trouble passing tests with latest lme4: I had to do the following hacks to get 'maxit' passed through all the right places (certainly indicates a need for refactoring on our side!)  With these changes, I can pass R CMD check ...

what do you think?

### CODE REVIEW

**Comment by vdorie** [comment]
So I've merged the changes in my local repository, but is there a release candidate for lme4? When I submitted the update to CRAN, everything was working fine, and now I see that the refit code has changed as well and summary isn't working for refitted bglmms.

**Comment by bbolker** [comment]
The release candidate is on Github and on the r-forge repository -- I could also send you the tarball if you want.    The `maxit` stuff was added in https://github.com/lme4/lme4/commit/9f14c47d34d89751d136796d282070a24cab1ed6 (I'm not sure why ...)  Let me know what else I can do to help (I didn't see summary broken, but maybe it wasn't in the test suite ...)

**Comment by vdorie** [comment]
Is there a specific commit to target, or will all changes to master before release be cosmetic?

It looks as if everything is working now, but I have still have to test on different architectures and with previous versions before I submit an update.

**Comment by bbolker** [comment]
I believe at this point all changes to master will be cosmetic.

I hope the addition of the maxit argument doesn't mess you up for testing
with previous versions. (If you're OK with using the default value of
`maxit` you might be able to get away with just passing named arguments
instead ...)

**Comment by vdorie** [comment]
As far as I can tell, everything is in order. I'll submit again today, unless you think there will be more changes before release.

**Comment by bbolker** [comment]
not that I know of, but it might not hurt to wait a day or so.  sorry for
the hassle.

**Comment by vdorie** [comment]
Thanks. Unless I hear otherwise, I'll plan on submitting on Friday.

**Pull request merged**
